### ISSUE TITLE
Feature request: add support for specifying samples directly

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [uab-cgds-worthey/quac#86]
**Describe the bug**
Currently, quac expects a certain directory structure to identify samples and bam/vcf files, which makes it difficult to use with existing pipelines, which may have a different folder structure. It would be nice to have a way to explicitly specify samples and files, so that users do not have to replicate the exact folder structure that quac expects.

**Additional context**
One way to do this would be to add support for something like [PEP](http://pep.databio.org/en/latest/), which can be as simple as a csv file, but also supports more complex project configurations. Snakemake already has native support for PEP, see [here](https://snakemake.readthedocs.io/en/stable/snakefiles/configuration.html#configuring-scientific-experiments-via-peps), so this should not be difficult to add to quac.

**Comment by ManavalanG** [comment]
@Redmar-van-den-Berg We have now implemented the requested change. Users can now provide input info in a config file via `--sample_config`. Documentation is [available here](https://quac.readthedocs.io/en/latest/input_output/) (please be sure use the `latest` version in readthedocs at the bottom right).
